import type { ProviderConfig, ProviderId } from '../../types/ai'

export const PROVIDERS_CONFIG: Record<ProviderId, ProviderConfig> = {
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    icon: 'Sparkles',
    placeholderKey: 'AIzaSy...',
    getKeyUrl: 'https://aistudio.google.com/app/apikey',
    helpText: 'Clé gratuite disponible instantanément sur Google AI Studio.',
    defaultModel: 'gemini-2.0-flash',
    models: [
      {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        description: 'Ultra rapide, multimodal et très précis. Idéal pour l’étude quotidienne.',
        badge: 'Recommandé',
        isRecommended: true,
        contextLength: '1M tokens',
      },
      {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        description: 'Excellence pour les dissertations, analyses complexes et longs devoirs.',
        badge: 'Raisonnement++',
        contextLength: '2M tokens',
      },
      {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        description: 'Version Flash 1.5, légère et véloce pour les questions rapides.',
        badge: 'Rapide',
        contextLength: '1M tokens',
      },
      {
        id: 'gemini-2.0-flash-lite',
        name: 'Gemini 2.0 Flash Lite',
        description: 'Consommation minimale de quota et latence la plus basse.',
        badge: 'Éco',
        contextLength: '1M tokens',
      },
    ],
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    icon: 'Flame',
    placeholderKey: 'mistral_...',
    getKeyUrl: 'https://console.mistral.ai/api-keys/',
    helpText: 'Modèles d’excellence européens, parfaits pour le français et les maths.',
    defaultModel: 'mistral-large-latest',
    models: [
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large',
        description: 'Modèle phare pour le raisonnement de haut niveau et la rédaction.',
        badge: 'Recommandé',
        isRecommended: true,
        contextLength: '128k tokens',
      },
      {
        id: 'mistral-small-latest',
        name: 'Mistral Small',
        description: 'Compromis idéal entre rapidité de réponse et rigueur.',
        badge: 'Équilibré',
        contextLength: '128k tokens',
      },
      {
        id: 'codestral-latest',
        name: 'Codestral',
        description: 'Spécialisé en informatique, programmation Python/JS/C++ et algorithmique.',
        badge: 'Code & NSI',
        contextLength: '256k tokens',
      },
      {
        id: 'open-mistral-nemo',
        name: 'Mistral NeMo',
        description: 'Modèle agile 12B performant pour les explications rapides.',
        badge: 'Rapide',
        contextLength: '128k tokens',
      },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    icon: 'Cpu',
    placeholderKey: 'sk-proj-...',
    getKeyUrl: 'https://platform.openai.com/api-keys',
    helpText: 'Plateforme OpenAI (GPT-4o, o1, o3-mini).',
    defaultModel: 'gpt-4o',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: 'Modèle omni intelligent et polyvalent pour toutes les matières.',
        badge: 'Recommandé',
        isRecommended: true,
        contextLength: '128k tokens',
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        description: 'Ultra rapide et très économique, excellent pour les quiz et révisions.',
        badge: 'Rapide',
        contextLength: '128k tokens',
      },
      {
        id: 'o3-mini',
        name: 'o3-mini',
        description: 'Modèle de réflexion poussée pour les problèmes difficiles de maths et sciences.',
        badge: 'Raisonnement STEM',
        contextLength: '200k tokens',
      },
      {
        id: 'o1',
        name: 'o1',
        description: 'Raisonnement profond étape par étape pour concours et prépa.',
        badge: 'Expert Supérieur',
        contextLength: '200k tokens',
      },
    ],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    icon: 'Brain',
    placeholderKey: 'sk-ant-api...',
    getKeyUrl: 'https://console.anthropic.com/settings/keys',
    helpText: 'Claude excelle dans la clarté pédagogique et la rédaction littéraire.',
    defaultModel: 'claude-3-7-sonnet-20250219',
    models: [
      {
        id: 'claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet',
        description: 'Dernière génération hybride avec capacités de réflexion avancée.',
        badge: 'Top Raisonnement',
        isRecommended: true,
        contextLength: '200k tokens',
      },
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        description: 'Excellence absolue en dissertation, philosophie, analyse de texte et code.',
        badge: 'Excellence',
        contextLength: '200k tokens',
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        description: 'Vitesse de réponse instantanée pour les questions directes et les définitions.',
        badge: 'Ultra Rapide',
        contextLength: '200k tokens',
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'Globe',
    placeholderKey: 'sk-or-v1-...',
    getKeyUrl: 'https://openrouter.ai/keys',
    helpText: 'Plateforme unifiée donnant accès à DeepSeek, Llama, Qwen, Mistral et bien d’autres.',
    defaultModel: 'deepseek/deepseek-chat',
    models: [
      {
        id: 'deepseek/deepseek-chat',
        name: 'DeepSeek V3',
        description: 'Modèle ouvert d’élite pour les sciences, langues et logique.',
        badge: 'Recommandé',
        isRecommended: true,
        contextLength: '64k tokens',
      },
      {
        id: 'deepseek/deepseek-r1',
        name: 'DeepSeek R1',
        description: 'Raisonnement pas-à-pas ouvert, idéal pour les démonstrations mathématiques.',
        badge: 'Raisonnement R1',
        contextLength: '64k tokens',
      },
      {
        id: 'meta-llama/llama-3.3-70b-instruct',
        name: 'Llama 3.3 70B',
        description: 'Grand modèle open-source polyvalent de Meta.',
        badge: 'Open Source',
        contextLength: '128k tokens',
      },
      {
        id: 'qwen/qwen-2.5-coder-32b-instruct',
        name: 'Qwen 2.5 Coder 32B',
        description: 'Spécialisé en informatique et programmation pour élèves et étudiants.',
        badge: 'Code Specialist',
        contextLength: '32k tokens',
      },
    ],
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode (Local / Custom)',
    icon: 'Terminal',
    placeholderKey: 'Optionnel ou clé token...',
    getKeyUrl: 'https://ollama.com',
    helpText: 'Serveur local OpenCode, Ollama, LM Studio ou API OpenAI-compatible privée.',
    defaultModel: 'deepseek-coder',
    allowCustomBaseUrl: true,
    defaultBaseUrl: 'http://localhost:11434/v1',
    models: [
      {
        id: 'deepseek-coder',
        name: 'DeepSeek Coder (Local)',
        description: 'Modèle local spécialisé en programmation et logique mathématique.',
        badge: 'Local',
        isRecommended: true,
        contextLength: '32k tokens',
      },
      {
        id: 'qwen2.5-coder:7b',
        name: 'Qwen 2.5 Coder 7B',
        description: 'Modèle léger optimisé pour tourner sur PC d’élève sans GPU lourd.',
        badge: 'Léger',
        contextLength: '32k tokens',
      },
      {
        id: 'llama3.2:3b',
        name: 'Llama 3.2 3B',
        description: 'Modèle ultra-compact idéal pour réponses rapides hors-ligne.',
        badge: 'Ultra Rapide',
        contextLength: '8k tokens',
      },
      {
        id: 'mistral:7b',
        name: 'Mistral 7B (Local)',
        description: 'Grand classique local pour l’aide aux devoirs en français.',
        badge: 'Français',
        contextLength: '8k tokens',
      },
    ],
  },
}

export function getProviderConfig(provider: ProviderId): ProviderConfig {
  return PROVIDERS_CONFIG[provider] || PROVIDERS_CONFIG.gemini
}

export function getAllProviders(): ProviderConfig[] {
  return Object.values(PROVIDERS_CONFIG)
}
